### PR TITLE
Github disables the Issues tab on forks

### PR DESCRIPTION
**Pull request by dandv**
Would be nice to know how this fork is different from the original.

Thanks!

### CODE REVIEW

**Comment by cwohlman** [comment]
Just added a simple feature to the package: https://github.com/bengott/meteor-avatar/pull/41

**Comment by dandv** [comment]
Looks like a useful feature. 

Since you've published a separate package, https://atmospherejs.com/cwohlman/avatar, it would be nice to mention in its README how it differs from the  original.

**Comment by cwohlman** [comment]
The package isn't actually intended to be used, I just published it since
meteor doesn't support using github urls.

**Comment by dandv** [comment]
Well, it does appear in Atmosphere searches and may add to the choice users have to make.

There's fortunately a simple solution: you can mark it as unmigrated, which will keep it installable, but hide it from searches:

```
meteor admin set-unmigrated cwohlman:avatar
```

In the meantime @bengott may also accept the PR.

Just trying to keep Atmosphere clean.

**Comment by dandv** [comment]
Hey @cwohlman,

Any change to unmigrate this package now that work has moved to https://github.com/meteor-utilities/avatar/ ?

```
meteor admin set-unmigrated cwohlman:avatar
```

**Comment by cwohlman** [comment]
Done

**Pull request closed without merging**
